name: CITest

on:
  push:
    branches: [ master ]
    
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Install OpenVPN
        run: |
          sudo apt-get --assume-yes --no-install-recommends install openvpn
          
      - name: CMD
        run: echo "Testing"
        
      - name: VPN IP
        run: curl https://api.ipify.org
          
          
        
       
