name: CITest

on:
  push:
    branches: [ master ]
    
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Install OpenVPN
        run: |
          sudo apt-get --assume-yes --no-install-recommends install openvpn
          echo "Testing"
          curl https://api.ipify.org
        
       
